Repository eprei/ft_transcendence, pull requests merged in 2023-07, with the labels that each got.

#49 docs: diagram 42 authentification
  docs/README.adoc
  docs/assets/authentification.svg
  docs/assets/docker.svg
  docs/index.html
Labels: documentation

#53 script: create cmd-back.sh
  Makefile
  scripts/cmd-back.sh
  scripts/create-env.sh
Labels: enhancement

#57 backend: remove spec files
  backend/src/app.controller.spec.ts
  backend/src/player/player.controller.spec.ts
  backend/src/player/player.service.spec.ts
Labels: enhancement

#58 42.svg upload bug fixed
  frontend/src/components/navigation/Navbar.module.css
Labels: bug

#54 Database entites and crud operations
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/channel/channel.controller.ts
  backend/src/channel/channel.module.ts
  backend/src/channel/channel.service.ts
  backend/src/channel/dto/create-channel.dto.ts
  backend/src/channel/dto/update-channel.dto.ts
  backend/src/friend/dto/create-friend.dto.ts
  backend/src/friend/dto/update-friend.dto.ts
  backend/src/friend/friend.controller.ts
  backend/src/friend/friend.module.ts
  backend/src/friend/friend.service.ts
  backend/src/match/dto/create-match.dto.ts
  backend/src/match/dto/update-match.dto.ts
  backend/src/match/match.controller.ts
  backend/src/match/match.module.ts
  backend/src/match/match.service.ts
  backend/src/message/dto/create-message.dto.ts
  backend/src/message/dto/update-message.dto.ts
  backend/src/message/message.controller.ts
  backend/src/message/message.module.ts
  backend/src/message/message.service.ts
  backend/src/player/dto/create-player.dto.ts
  backend/src/player/dto/update-player.dto.ts
  backend/src/player/player.controller.ts
  backend/src/player/player.module.ts
  backend/src/player/player.service.ts
  backend/src/typeorm/Player.ts
  backend/src/typeorm/channel.entity.ts
  backend/src/typeorm/friend.entity.ts
  backend/src/typeorm/match.entity.ts
  backend/src/typeorm/message.entity.ts
  backend/src/typeorm/user.entity.ts
  backend/src/types/Player.ts
  backend/src/user/dto/create-user.dto.ts
  backend/src/user/dto/update-user.dto.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
  backend/uploads/user1.webp
  backend/uploads/user2.webp
  backend/uploads/user3.webp
  backend/uploads/user4.webp
  backend/uploads/user5.webp
  backend/uploads/user6.webp
Labels: enhancement

#55 docs: database
  docs/README.adoc
  docs/assets/data.png
  docs/assets/docker.svg
  docs/index.html
Labels: documentation

#44 frontend: simple pong
  frontend/src/components/pong/BoardGame.module.css
  frontend/src/components/pong/BoardGame.tsx
  frontend/src/pages/Game.tsx
Labels: enhancement

#63 all resources about /tmp had been deleted
  frontend/src/App.tsx
  frontend/src/components/tempLogin/TempForm.module.css
  frontend/src/components/tempLogin/TempForm.tsx
  frontend/src/components/tempLogin/TempPlayerLi.module.css
  frontend/src/components/tempLogin/TempPlayerLi.tsx
  frontend/src/components/tempLogin/TempPlayerList.module.css
  frontend/src/components/tempLogin/TempPlayerList.tsx
  frontend/src/pages/TempLogin.module.css
  frontend/src/pages/TempLogin.tsx
  frontend/src/types/Player.ts
Labels: enhancement

#68 frontend: remove import react
  frontend/src/components/profile/ClickableIcon.tsx
  frontend/src/components/profile/Friend.tsx
  frontend/src/components/profile/StatisticElement.tsx
  frontend/src/components/profile/UserInformation.tsx
Labels: enhancement

#69 frontend: few fix pong component
  frontend/src/components/pong/BoardGame.tsx
Labels: enhancement

#66 Profil page shows database information
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/strategies/auth42.strategy.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
  frontend/src/components/profile/MainProfile.tsx
  frontend/src/components/profile/StatisticElement.tsx
  frontend/src/components/profile/Statistics.tsx
  frontend/src/components/profile/UserInformation.tsx
Labels: enhancement

#72 R real user in front
  backend/src/auth/auth.service.ts
  backend/src/auth/strategies/auth42.strategy.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
  frontend/src/App.tsx
  frontend/src/components/error/Error.tsx
  frontend/src/components/profile/MainProfile.tsx
  frontend/src/components/profile/Statistics.tsx
  frontend/src/components/profile/UserInformation.tsx
  frontend/src/pages/MainProfile.module.css
  frontend/src/pages/MainProfile.tsx
  frontend/src/pages/Profile.module.css
  frontend/src/pages/Profile.tsx
  frontend/src/store/index.tsx
  frontend/src/store/user.tsx
  frontend/src/types/UserData.ts
Labels: enhancement

#71 2fa is here
  backend/package-lock.json
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/guards/activate2fa.guard.ts
  backend/src/auth/guards/authenticated.guard.ts
  backend/src/auth/guards/oauth.guard.ts
  backend/src/auth/guards/totp.guard.ts
  backend/src/types/User.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
  frontend/src/App.tsx
  frontend/src/components/TFATurnOn/CodeQR.module.css
  frontend/src/components/TFATurnOn/CodeQR.tsx
  frontend/src/components/TFAVerify/TwoFactorVerificationBox.module.css
  frontend/src/components/TFAVerify/TwoFactorVerificationBox.tsx
  frontend/src/components/profile/SwitchButton.module.css
  frontend/src/components/profile/UserInformation.tsx
  frontend/src/pages/TFA.module.css
  frontend/src/pages/TFAAuthenticate.tsx
  frontend/src/pages/TFATurnOn.tsx
Labels: enhancement

#73 R profile refactor
  frontend/src/components/profile/Statistics.tsx
  frontend/src/components/profile/UserInformation.tsx
  frontend/src/pages/MainProfile.tsx
Labels: enhancement

#79 frontend: remove extra curly bracket
  frontend/src/components/profile/Friend.tsx
Labels: improvement

#77 UserLambda hotfix
  frontend/src/components/profile/StatisticsLambda.tsx
  frontend/src/pages/UserLambda.tsx
Labels: bug

#78 E edit nickname
  backend/src/user/dto/update-nickname.dto.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
  frontend/src/components/profile/ClickableIcon.tsx
  frontend/src/components/profile/UserInformation.tsx
Labels: enhancement

#82 makefile: make build
  Makefile
Labels: enhancement, makefile

#83 Fix for compile-time issues
  backend/src/user/user.controller.ts
  frontend/src/App.tsx
  frontend/src/components/TFATurnOn/CodeQR.module.css
  frontend/src/components/TFATurnOn/CodeQR.tsx
  frontend/src/components/UserLambda/UserLambdaInformation.tsx
  frontend/src/components/pong/BoardGame.tsx
  frontend/src/components/profile/StatisticsLambda.tsx
Labels: bug

#80 frontend: profile add link on the username
  frontend/src/components/profile/Friend.tsx
Labels: enhancement

#85 R load user in store
  frontend/src/App.tsx
  frontend/src/RootLayout.tsx
  frontend/src/components/error/Error.tsx
  frontend/src/pages/MainProfile.tsx
Labels: improvement

#86 changed function with axios to fetch and uninstall axios
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/profile/UserInformation.tsx
Labels: improvement

#87 logout button in navbar not moving links anymore
  frontend/src/components/navigation/Navbar.module.css
  frontend/src/components/navigation/Navbar.tsx
Labels: improvement

#90 Global usage of authenticated.guard
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/guards/authenticated.guard.ts
  backend/src/decorators/public.decorator.ts
  backend/src/user/user.controller.ts
Labels: Security

#88 Friends can now be managed
  backend/src/app.service.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/friend/friend.controller.ts
  backend/src/friend/friend.module.ts
  backend/src/friend/friend.service.ts
  backend/src/typeorm/friend.entity.ts
  backend/src/typeorm/user.entity.ts
  backend/src/user/dto/create-user.dto.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/icon/accept_friend.svg
  frontend/src/assets/icon/add_friend.svg
  frontend/src/components/profile/AddFriendsBtn.module.css
  frontend/src/components/profile/AddFriendsBtn.tsx
  frontend/src/components/profile/CustomLink.tsx
  frontend/src/components/profile/Friend.tsx
  frontend/src/components/profile/FriendList.tsx
  frontend/src/components/profile/OtherUsers.module.css
  frontend/src/components/profile/OtherUsers.tsx
  frontend/src/components/profile/SeeMatchHistoryBtn.tsx
  frontend/src/pages/MainProfile.tsx
Labels: enhancement

#91 Victorires -> Victories
  frontend/src/components/profile/StatisticsLambda.tsx
Labels: improvement

#93 game: websocket
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/pong/dto/create-pong.dto.ts
  backend/src/pong/dto/update-pong.dto.ts
  backend/src/pong/entities/pong.entity.ts
  backend/src/pong/pong.gateway.ts
  backend/src/pong/pong.module.ts
  backend/src/pong/pong.service.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/pong/BoardGame.tsx
Labels: enhancement

#92 warning when reloading profile fix
  frontend/src/pages/MainProfile.tsx
Labels: bug

#94 RootLayout loader is doing the dispatch
  frontend/src/RootLayout.tsx
Labels: improvement

#96 R friend backend improvement
  backend/src/friend/friend.controller.ts
  backend/src/user/user.service.ts
Labels: bug

#98 E play
  backend/src/app.module.ts
  backend/src/room/dto/create-room.dto.ts
  backend/src/room/room.controller.ts
  backend/src/room/room.module.ts
  backend/src/room/room.service.ts
  backend/src/types/Room.ts
  backend/src/user/user.service.ts
  frontend/src/App.tsx
  frontend/src/components/navigation/Navbar.tsx
  frontend/src/components/play/MatchSystemBtn.module.css
  frontend/src/components/play/MatchSystemBtn.tsx
  frontend/src/pages/GameLauncher.tsx
  frontend/src/pages/Play.module.css
  frontend/src/pages/Play.tsx
Labels: enhancement

#101 backend: ignore env file
  backend/src/app.module.ts
Labels: Security

#103 backend: use a environment variable for URLs
  backend/src/app.service.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/strategies/auth42.strategy.ts
  backend/src/main.ts
  backend/src/user/user.service.ts
  docker-compose.yml
Labels: improvement
